Все-таки нужен отдельный метод модификации юзера для того, чтобы удавалось изменять данные пользователя.
siporqueno/let-me-rent pull request #102
Opened 2022-05-19 14:24 UTC by Daria-pugacheva

Все-таки нужен отдельный метод модификации юзера. При использовании конвертера нужен полный ДТО с паролями, а у меня при модификации пароли не летят с фронта. (если использовать существующий метод save , то вылетают ошибки).
Предлагаю, конвертер под модификацию не менять. А все-таки оставить просто отдельный предложенный мной метод в сервисе.
Дмитрий уже одобрял эту мою редакцию, но нужно два ревьюера на PR , поэтому его добавляю.
Ну и Артема тоже зову на одобрение, т.к. как раз ему моя редакция не нравилась. Но она оказалась рабочей, а его вариант как раз нет. (я только сейчас смогла запуститься и посмотреть в работе код)

2022-05-19 14:27 UTC, Haazaad commented
> Все-таки нужен отдельный метод модификации юзера. При использовании конвертера нужен полный ДТО с паролями, а у меня при модификации пароли не летят с фронта. (если использовать существующий метод save , то вылетают ошибки). Предлагаю, конвертер под модификацию не менять. А все-таки оставить просто отдельный предложенный мной метод в сервисе. Дмитрий уже одобрял эту мою редакцию, но нужно два ревьюера на PR , поэтому его добавляю. Ну и Артема тоже зову на одобрение, т.к. как раз ему моя редакция не нравилась. Но она оказалась рабочей, а его вариант как раз нет. (я только сейчас смогла запуститься и посмотреть в работе код)

В очередной раз не согласен.
Есть метод получения пользователя из бд по его username или id, что мешает достать его из Бд и потом поменять необходимые поля, зачем городить огород?

2022-05-19 14:28 UTC, Haazaad requested changes
Не согласен с предложенным подходом

2022-05-19 17:58 UTC, Daria-pugacheva commented
так.... Я же именно это и делаю в методе modifyUser: вытаскиваю по имени пользователя и меняю поля и сохраняю. Что не так? Вот ровно то, что ты написал...

2022-05-20 12:45 UTC, framzik approved these changes

2022-05-22 12:52 UTC, Daria-pugacheva commented
Артем, да, так изменение функционирует.  НО! там получается, в начале метода сохранения проверка на айдишник. Я запустилась и заметила, что в таком случае ломается добавление юзера: бэк пытается проверить по айдишнику, есть ли юзер в базе, а юзер при сохранении прилетает в этот метод без айдишника. Т.е. если такое обновление добавлять, то изменяется юзер хорошо, но перестает регистрироваться...

2022-05-23 13:17 UTC, Haazaad approved these changes

2022-05-23 13:19 UTC, merged