Lmr 15
siporqueno/let-me-rent pull request #2
Opened 2022-04-10 14:44 UTC by framzik

начальная инициализация БД и сущностей

2022-04-10 15:01 UTC, Haazaad commented
А зачем мержить в master?

2022-04-10 15:07 UTC, Haazaad requested changes

2022-04-10 15:07 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +    private String brand;
Лучше на верное сделать дополнительные таблички "Категория" и "Производитель"

2022-04-10 15:07 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +    public Instrument(String title, String brand, String description, BigDecimal fee, User owner, List<Picture> pictures) {
В таком случае лучше использовать аннотацию AllArgsConstructor

2022-04-10 15:07 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/entity/Picture.java
> +public class Picture {
А действительно картинки надо хранить в БД, может подумать в сторону хранения на каком-нибудь шаренном файсторе и в БД хранить ссылку на картинку?

2022-04-10 15:34 UTC, Daria-pugacheva commented
По составу сущностей у меня вопрос: Не увидела в Instrument списка Rent и в Rent нет инфо про Instrument.
Насколько я понимаю, календарь занятости для инструмента мы ведь будем строить на основе данных из его рент?
И еще я по структуре сайта предлагала добавить в инструмент еще поле про депозит (размер залога). Это, наверное, несложно будет.

2022-04-10 15:41 UTC, Haazaad commented
Думаю еще не хватает таблички "Заказы", для отслеживания кто и какой инструмен взял в аренду

2022-04-10 15:54 UTC, Daria-pugacheva commented
В теории, если в таблице rent будет инфо об инструменте, то будет связка, кто какой инструмент арендует, не?

2022-04-10 16:22 UTC, siporqueno commented
1) По депозиту, мне кажется, что в Instruement нужно добавить поле "Стоимость", на основе которой и будет считаться депозит, для начала она будет просто отображаться. Самый простой способ считать залог - 100% от стоимости для всех. всегда. Можно усложнить и снижать его по нарастанию числа рент. Можно ещё усложнить и оценивать качество ренты.
2) По сущностям, мне кажется в Rent надо заменить поле User lessor на Instrument instrument. В инструменте уже есть owner он же lessor, поскольку субаренды у нас для простоты пока по крайней мере нет. В Instrument добавить поле List<Rent> rents.
3) По картинкам, помню Ушаровский нам объяснял, что картинки в базу надо класть только при необходимости. У него это в проекте осталось так, потому что при разворачивании на Heroku по другому не получалось.

2022-04-10 16:58 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +    public Instrument(String title, String brand, String description, BigDecimal fee, User owner, List<Picture> pictures) {
не правильно в конструктор Id передавать, он автоикремент у нас

2022-04-10 17:19 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +    private String brand;
поменял

2022-04-10 17:20 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/entity/Picture.java
> +public class Picture {
сделал пока что в бд с картинкми будет просто url храниться

2022-04-10 17:21 UTC, framzik commented
>

2022-04-10 17:23 UTC, framzik commented
> 1. По депозиту, мне кажется, что в Instrument нужно добавить поле "Стоимость", на основе которой и будет считаться депозит, для начала она будет просто отображаться. Самый простой способ считать залог - 100% от стоимости для всех. всегда. Можно усложнить и снижать его по нарастанию числа рент. Можно ещё усложнить и оценивать качество ренты.
> 2. По сущностям, мне кажется в Rent надо заменить поле User lessor на Instrument instrument. В инструменте уже есть owner он же lessor, поскольку субаренды у нас для простоты пока по крайней мере нет. В Instrument добавить поле List rents.
> 3. По картинкам, помню Ушаровский нам объяснял, что картинки в базу надо класть только при необходимости. У него это в проекте осталось так, потому что при разворачивании на Heroku по другому не получалось.

1. поправил
2. Учел замечание Дарьи, добавил в инструмент ренты, а в ренты инструменты, мне кажеться логично тут сделать много ко многим, так как в 1 аренде, можно набрать несколько инструментов
3. По картинкам - передедлал чтобы хранить только ссылку на картинку.

2022-04-10 18:58 UTC, siporqueno commented
Да, видимо можно в одну ренту много инструментов. У ренты есть дата начала и дата окончания. Каждый инструмент имеет свой график доступности. То есть в ренту будут класться инструменты, частично или полностью доступные в период ренты. Тогда в Rent должны быть RentItems, а в них уже поля с Instrument. А у каждого RentItem своя дата начала и окончания ренты конкретного инструмента, который получается пересечением времени ренты и времени доступности инструмента. То есть мой изначальный Rent превращается в RentItem. Осталось теперь понять, как изменится фронт.

2022-04-10 19:24 UTC, siporqueno reviewed
Да, видимо можно в одну ренту много инструментов. У ренты есть дата начала и дата окончания. Каждый инструмент имеет свой график доступности. То есть в ренту будут класться инструменты, частично или полностью доступные в период ренты. Тогда в Rent должны быть RentItems, а в них уже поля с Instrument. А у каждого RentItem своя дата начала и окончания ренты конкретного инструмента, которые получаются пересечением времени ренты и времени доступности инструмента. То есть мой изначальный Rent превращается в RentItem. Осталось теперь понять, как изменится фронт.

2022-04-11 17:01 UTC, Haazaad requested changes

2022-04-11 17:01 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/entity/Category.java
> +    public Category(String name, String description, List<Instrument> instruments) {
Может проще сделать Builder для сущностей?
Аннотация Builder у lombook есть

2022-04-12 09:14 UTC, merged

2022-04-12 15:29 UTC, Daria-pugacheva commented on source/core/src/main/java/ru/letmerent/core/entity/Category.java
> +    public Category(String name, String description, List<Instrument> instruments) {
Да, вроде же у нас не много полей в сущностях и сложных особо нет, чтобы билдер применять? Это я, конечно, чисто теоретически, исходя из того, что на курсе по паттернам говорили, что билдер для масштабных созданий.