Lmr 32
siporqueno/let-me-rent pull request #25
Opened 2022-04-20 19:14 UTC by framzik

добавил логику с интервалами занятости

2022-04-21 05:41 UTC, Haazaad requested changes

2022-04-21 05:41 UTC, Haazaad commented on source/core/src/main/resources/db/changelog/changes/sql/v3_add_initial_data.sql
> +insert into orders (renter, start_date, end_date, total_rent_price)
start_date, end_date можно опустить в схеме по дефолту им выставлены значения, если не передаются

2022-04-21 05:41 UTC, Haazaad commented on source/core/src/test/java/ru/letmerent/core/converters/InstrumentConverterTest.java
> +    void instrumentDtoFromInstrument() {
какую часть кода тестирует данные тест?

2022-04-21 07:15 UTC, framzik commented on source/core/src/main/resources/db/changelog/changes/sql/v3_add_initial_data.sql
> +insert into orders (renter, start_date, end_date, total_rent_price)
я видел, показалось логичным закинуть данные, максимально приближенные к реальным

2022-04-21 07:16 UTC, framzik commented on source/core/src/test/java/ru/letmerent/core/converters/InstrumentConverterTest.java
> +    void instrumentDtoFromInstrument() {
При преобразовании инструмента в InstrumentDto, intervals инициализируются валидными данными

2022-04-21 07:37 UTC, Haazaad requested changes

2022-04-21 07:37 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/repositories/OrderItemRepository.java
> +    List<OrderItem> findAllByInstrument(Instrument instrument);
Очень плохое решение, вот прям очень плохое, лучше поиск по ид иструмента

2022-04-21 07:43 UTC, Haazaad requested changes

2022-04-21 07:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +import lombok.AllArgsConstructor;
Зачем?

2022-04-21 07:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +@AllArgsConstructor
Зачем?

2022-04-21 07:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/entity/OrderItem.java
> +@AllArgsConstructor
Зачем?

2022-04-21 08:01 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/repositories/OrderItemRepository.java
> +    List<OrderItem> findAllByInstrument(Instrument instrument);
согласен, исправил

2022-04-21 08:01 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +import lombok.AllArgsConstructor;
убрал

2022-04-21 08:01 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +@AllArgsConstructor
убрал

2022-04-21 08:01 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/entity/OrderItem.java
> +@AllArgsConstructor
убрал

2022-04-21 08:23 UTC, Haazaad requested changes

2022-04-21 08:23 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +
Зачем?
Сущность ппомечена аннотацией Data. там по умолчанию есть геттеры и сеттеры, зачем писать такой монструозный конструктор?
проще реализовать билдер

2022-04-21 08:23 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/entity/OrderItem.java
> +    public OrderItem(Order order, Instrument instrument, LocalDateTime startDate, LocalDateTime endDate, BigDecimal rentPrice) {
аналогично предыдущему замечанию

2022-04-21 09:27 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/entity/Instrument.java
> +
как по мне - дело вкуса

2022-04-21 09:27 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/entity/OrderItem.java
> +    public OrderItem(Order order, Instrument instrument, LocalDateTime startDate, LocalDateTime endDate, BigDecimal rentPrice) {
аналогично

2022-04-21 10:13 UTC, Haazaad approved these changes

2022-04-21 10:18 UTC, siporqueno reviewed
Поскольку на фронте интервалы будут отображаться от самого крайнего по времени начала (он будет отображен первым) к самому первому по времени начала, эти интервалы надо бы отсортировать по убыванию даты начала интервала.

2022-04-21 18:56 UTC, framzik commented
> 

внес правки, надеюсь я правильно понял: интервал  с самым ранним startDate будет последним

2022-04-22 09:15 UTC, siporqueno commented
> > 
> 
> внес правки, надеюсь я правильно понял: интервал с самым ранним startDate будет последним

Да, соответственно с самым поздним startDate - первым. Его фронт возьмет первым и отобразит в первой строчке таблицы интервалов. Перегнать (отразить) интервалы занятости в интервалы доступности сложно будет? Потенциальному арендатору мне кажется нужны именно интервалы доступности.

2022-04-23 10:46 UTC, siporqueno approved these changes

2022-04-23 10:55 UTC, merged