Lmr 5
siporqueno/let-me-rent pull request #32
Opened 2022-04-24 16:22 UTC by framzik

Работа с картинками.

2022-04-25 06:43 UTC, Haazaad requested changes

2022-04-25 06:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/controller/PictureController.java
> +    @GetMapping("/all/{instrumentId}")
В чем смысл получения только имен?
В инструментах вроде как есть коллекция картинок

2022-04-25 06:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/controllers/InstrumentController.java
> +        InstrumentInfoDto infoDto = instrumentService.getInstrumentById(id)
А почему orElse(null)?
Вроде как исключение, что не найдена сущность

2022-04-25 06:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentInfoDto.java
> +    List<String> picturesNames;
В чем отличие от List< Picture >?

2022-04-25 06:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/exceptions/BaseException.java
> +    public BaseException(String message) {
в чем смысл?

2022-04-25 06:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public PictureStorageServiceImpl(PictureRepository pictureRepository,
Вот это не очень хорошо.
Предполагается ли создание различных экземпляров данного сервиса или он будет один?

2022-04-25 06:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public void save(MultipartFile file, Instrument instrument) {
А где добавление оригинального имени файла в метаданные нового файла?

2022-04-25 06:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public List<String> loadInstrumentPicturesName(Instrument instrument) {
Зачем прокидывать целый объект, если все равно поиск идет только по id

2022-04-25 06:43 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public void deletePictures(Instrument instrument, List<Long> pictureIds) {
Зачем целый объект инструментов и одновременно и список ид картинок?

2022-04-25 07:20 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public void save(MultipartFile file, Instrument instrument) {
а для чего нам это?

2022-04-25 07:32 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public void save(MultipartFile file, Instrument instrument) {
Т.е. выгрузка будет только с нашими именами файлов и больше никакими?

2022-04-25 18:09 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public PictureStorageServiceImpl(PictureRepository pictureRepository,
думаю будет 1

2022-04-25 18:10 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public void save(MultipartFile file, Instrument instrument) {
я думал да

2022-04-25 18:26 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/controller/PictureController.java
> +    @GetMapping("/all/{instrumentId}")
исправил

2022-04-25 18:26 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/controllers/InstrumentController.java
> +        InstrumentInfoDto infoDto = instrumentService.getInstrumentById(id)
исправил

2022-04-25 18:26 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentInfoDto.java
> +    List<String> picturesNames;
убрал

2022-04-25 18:26 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/exceptions/BaseException.java
> +    public BaseException(String message) {
убрал

2022-04-25 18:26 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public void save(MultipartFile file, Instrument instrument) {
добаdил загрузку по id

2022-04-25 18:27 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public List<String> loadInstrumentPicturesName(Instrument instrument) {
исправил

2022-04-25 18:27 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public void deletePictures(Instrument instrument, List<Long> pictureIds) {
если мы хотим удалить не все картинки, передаем список Id который удалить

2022-04-25 18:29 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public PictureStorageServiceImpl(PictureRepository pictureRepository,
Тогда резонно сделать метод init() с аннотацией PreAuthorize, где проинициализировать необходимые поля класса и сервис уже будет синглтоном

2022-04-25 18:36 UTC, Haazaad requested changes

2022-04-25 18:36 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/exceptions/FileUploadExceptionAdvice.java
> +        return ResponseEntity.status(HttpStatus.EXPECTATION_FAILED).body("File too large!");
Думаю лучше возвращать ApplicationError сразу

2022-04-25 18:36 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +        Optional<Picture> oPicture = pictureRepository.findById(pictureId);
Если Optional, то где обработка исключений, в случае, если ничего не найдено?

2022-04-25 18:36 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public void deletePictures(Long instrumentId, List<Long> pictureIds) {
Может ли одно изображение принадлежать различным инструментам?

2022-04-25 19:11 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public void deletePictures(Long instrumentId, List<Long> pictureIds) {
нет

2022-04-25 19:12 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +        Optional<Picture> oPicture = pictureRepository.findById(pictureId);
86-87 строка

2022-04-25 19:18 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/exceptions/FileUploadExceptionAdvice.java
> +        return ResponseEntity.status(HttpStatus.EXPECTATION_FAILED).body("File too large!");
поправил

2022-04-25 19:19 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/PictureStorageServiceImpl.java
> +    public PictureStorageServiceImpl(PictureRepository pictureRepository,
с этим не встречался, если можешь- кинь как надо сделать, я чет быстро не смог разобраться

2022-05-01 14:13 UTC, siporqueno approved these changes

2022-05-03 08:58 UTC, merged