Fixed serialization, deserialization issue of cart Lmr 29and20and37
siporqueno/let-me-rent pull request #39
Opened 2022-04-28 10:51 UTC by siporqueno

1) Для того чтобы десериализация корзины полностью заработала реализовал OrderItemDtoDeserializer. Без него в корзине поле items после десериализации было null.

2) Поправил логику добавления в корзину, чтобы в неё нельзя было добавить два раза один и тот же инструмент с одним и тем же периодом аренды.

2022-04-28 11:06 UTC, TepbI4 approved these changes

2022-04-28 17:30 UTC, framzik approved these changes

2022-04-29 10:25 UTC, Daria-pugacheva approved these changes

2022-04-29 10:26 UTC, Daria-pugacheva approved these changes
Только с разрешением конфликтов внимательно, чтобы все, нажитое непосильным трудом, сохранилось :))

2022-04-29 10:51 UTC, Haazaad commented
А это нормально, что мерж идет в ветку [LMR-29and20and37](https://github.com/siporqueno/let-me-rent/tree/LMR-29and20and37)?

2022-04-29 10:53 UTC, Haazaad requested changes
Пролить актуальные изменения из develop, устранить конфликты

2022-04-29 10:53 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/configs/RedisConfig.java
> +//        template.setValueSerializer(new GenericJackson2JsonRedisSerializer());
Убрать комментарии, которые не нужны

2022-04-29 12:00 UTC, siporqueno commented
> Только с разрешением конфликтов внимательно, чтобы все, нажитое непосильным трудом, сохранилось :))

) Буду очень внимателен

2022-04-29 12:05 UTC, siporqueno commented
> А это нормально, что мерж идет в ветку [LMR-29and20and37](https://github.com/siporqueno/let-me-rent/tree/LMR-29and20and37)?

Дорабатывал корзину, которая в ветке LMR-29and20and37, поэтому собираюсь туда сделать мерж, туда же пролить девелоп и устранить конфликты, если появятся.

2022-04-29 12:06 UTC, siporqueno commented on source/core/src/main/java/ru/letmerent/core/configs/RedisConfig.java
> +//        template.setValueSerializer(new GenericJackson2JsonRedisSerializer());
Уберу

2022-04-29 14:58 UTC, merged