Сделан набросок по фильтрации. (пока накидала и даже не смотрела,как…
siporqueno/let-me-rent pull request #41
Opened 2022-04-29 13:59 UTC by Daria-pugacheva

Сделан набросок по фильтрации. (пока накидала и даже не смотрела, как это выводится, и на бэк не заглядывала с пристрастием, но идея, думаю,  ясна)

Просьба к Денису посмотреть, удобно будет, если таким вот образом передавать запрос на бэк (ввела доп.параметр, получается, в запрос loadTools). В таком же ключе думаю добавить в этот метод и инфо о кол-ве элементов на странице.

2022-04-30 15:31 UTC, siporqueno commented
1) Поправил параметры по сортировке как обсуждали.
2) В функцию putIntoCart вернул даты начала и окончания аренды, они будут нужны чтобы положить в корзину. Перед запросом на бэк по добавлению в корзину добавил проверку, что даты есть и вывод алерта если хоть одной нет.

2022-04-30 15:43 UTC, siporqueno approved these changes

2022-05-01 12:43 UTC, siporqueno commented
> Могу ошибаться, но кнопку Арендовать я из общей таблицы убирала и соответствующий метод tryToRent из js тоже уходит - я его убирала. Тоже надо внимательно при слиянии. Ну, с ним, впрочем легко: если увижу, то просто опять удалю

Да, он остался в этой ветке, я его при мерже девелопа не убрал. Надо убрать его да мержить, мне кажется.

2022-05-02 12:45 UTC, siporqueno requested changes

2022-05-02 12:45 UTC, siporqueno commented on source/core/src/main/resources/static/tools-list/tools-list.html
>      </div>
```suggestion
    </div>
    <select name="Кол-во элементов " class="form-select" aria-label="Default select example" ng-model="size" >
        <option value="1" >1</option>
        <option value="2">2</option>
        <option value="3">3</option>
    </select>

    <br/>
    <br/>
```

2022-05-02 12:45 UTC, siporqueno commented on source/core/src/main/resources/static/tools-list/tools-list.html
> +    </div>
Заменил на <select выше
```

2022-05-02 12:45 UTC, siporqueno commented on source/core/src/main/resources/static/tools-list/tools-list.js
> +                sort: sorting,
```suggestion
size: $scope.size,
                sort: sorting,
```

2022-05-02 12:45 UTC, siporqueno commented on source/core/src/main/resources/static/tools-list/tools-list.js
> +                sort: sorting,
$scope.size идет из select

2022-05-02 14:26 UTC, tatiananosova approved these changes

2022-05-02 14:40 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/tools-list/tools-list.html
> +    </div>
При таком подходе не уверена, что когда человек выберет сначала сортировку, а потом кол-во страниц, то сохранится его выбор по сортировке. Но если оно по какой-то причине срабатывает корректно, то так, безусловно, лаконичнее, чем я накрутила.

2022-05-02 14:42 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/tools-list/tools-list.html
>      </div>
Класс! А я не догадалась перекинуть из такого варианта выборки через ng-model размер страницы.. Все смотрела, как повесить действие, а оно на кнопки хорошо ложится, а на option никак :))  Только надо поменять 1, 2 и 3 на 10, 25 и 50, наверное? и написать "кол-во элементов на странице", так? И еще момент: при таком подходе после того, как пользователь выбирает кол-во страниц, вроде ж никакой метод не вызывается, т.е. не произойдет заново загрузка списка инструментов (не прилетит новый Page нужного размера? Или я недопонимаю?

2022-05-02 14:44 UTC, Daria-pugacheva reviewed
Написала комментарии - есть сомнения, что такой вариант сработает корректно со всеми сортировками и выборами кол-ва элементов. Если работает, то это очень круто!  и я ЗА

2022-05-02 15:18 UTC, siporqueno commented on source/core/src/main/resources/static/tools-list/tools-list.html
>      </div>
"Только надо поменять 1, 2 и 3 на 10, 25 и 50, наверное? и написать "кол-во элементов на странице", так?" - Да, конечно.

После выбора кол-ва страниц не прилетит, нужно ещё фильтрацию нажать при таком подходе.

2022-05-02 15:35 UTC, siporqueno commented
> Написала комментарии - есть сомнения, что такой вариант сработает корректно со всеми сортировками и выборами кол-ва элементов. Если работает, то это очень круто! и я ЗА

Надо будет ещё попробовать в select приделать ng-change="loadTools()" и тогда есть надежда, что при нажатии на фильтрацию, сортировку, выбор кол-ва элементов на странице все будет применяться сразу.

2022-05-02 20:22 UTC, siporqueno commented
Сделал выбор кол-ва элементов на странице и сортировки через два select. Выбор варианта вызывает loadTools, выбранный вариант кладется в модель, как и фильтры, поэтому при нажатии кнопки "Применить фильтры" или выборе кол-ва элементов или выборе сортировки все что в модели (фильтры, кол-во элементов, сортировка) берется как параметры и улетает на бэк.

Не могу сделать в selected, чтобы какой-то вариант (10) был выбран по умолчанию. Добавление атрибута selected или ng-selected="true" в option не помогает.

2022-05-03 15:25 UTC, tatiananosova approved these changes
Сортировка работает. Фильтрация - нет, её я так понимаю в этой ветке нет, так как ошибок программа не выдает. Надо красоту навести, но это можно в другой ветке сделать, чтоб не задерживать эту фичу.

2022-05-03 21:29 UTC, siporqueno commented
> 

Да, давайте мержить уже этот ПР.

2022-05-04 10:13 UTC, merged