Lmr 18
siporqueno/let-me-rent pull request #5
Opened 2022-04-11 20:07 UTC by Daria-pugacheva

Добавлены две DTO. Для авторизации, возможно, еще появятся (смотря, как коллеги напишут. В магазине мы использовали для авторизации такие по сути DTO классы, как AuthReponse и AuthRequest).
Как-то по тому, что надо отображать на фронте, пока из двух DTO-шек все прекрасно вытягивается. Но при этом внутри самих UserDto и InstrumentDto фигурируют сущности, а не DTO-классы. Вроде, ничего категорически секретного в них нет и не вижу, необходимости их перегонять. Но, может, я это зря так мыслю.
И есть такой момент, что для заполнения инфо о списке арендованных и сданных в аренду инструментов, а также календаря занятости, данные вытягиваем по цепочке из полей. Сегодня обсудили, что это нормально решается запросом в базу. Но я пока переживаю, чтобы оно правда нормально вытягивалось без всяких LAZY-LOADов и зависаний. 
Про корзину пока не думала.
Фронт пока еще не правила под изменения по сущностям и DTO. Буду корректировать завтра утром.

2022-04-12 06:39 UTC, siporqueno reviewed
Считаю, что для инструмента нужно сделать два отдельных DTO: для списка и для странички инструмента. Из того, что для списка, убрать orderItems и pictures. Экономия будет при ответе на запрос о всех инструментах. Поле Picture avatarPicture заменил бы на String avatarPictureUrl.

2022-04-12 10:19 UTC, Haazaad commented
> Считаю, что для инструмента нужно сделать два отдельных DTO: для списка и для странички инструмента. Из того, что для списка, убрать orderItems и pictures. Экономия будет при ответе на запрос о всех инструментах. Поле Picture avatarPicture заменил бы на String avatarPictureUrl.

Зачем городить огород?
Это решается на уровне контроллера

2022-04-12 10:21 UTC, Haazaad requested changes

2022-04-12 10:21 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/dtos/UserDto.java
> +    private List<OrderDto> orders;
А это то тут зачем?

2022-04-12 10:21 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/dtos/InstrumentDto.java
> +    private List<OrderItemDto> orderItems;  // отсюда на страницу инструмента будет выцепляться инфо для календаря занятости
Зачем?

2022-04-12 15:33 UTC, Daria-pugacheva commented on source/core/src/main/java/ru/letmerent/core/dtos/UserDto.java
> +    private List<OrderDto> orders;
В смысле? Зачем UserDto? Ну, юзера уж точно целиком на фронт кидать не стоит?

2022-04-12 15:36 UTC, Daria-pugacheva commented on source/core/src/main/java/ru/letmerent/core/dtos/InstrumentDto.java
> +    private List<OrderItemDto> orderItems;  // отсюда на страницу инструмента будет выцепляться инфо для календаря занятости
Считаешь, не надо пытаться сделать две разные Dto? или идея с пачкой полей плохая? 
По двум разным Dto пока есть отклик от Николая, что хорошо бы сделать. Я пока не берусь авторитетно судить, даст ли это какую-то экономию. Но с фронта визуально удобнее забирать сразу поля из Dto, чем лезть внутрь сущности и оттуда выцеплять поля, поэтому такая мысль и родилась.

2022-04-13 09:54 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/dtos/UserDto.java
> +    private List<OrderDto> orders;
Зачем при запросе пользователя выводить в дополнение его заказы?

2022-04-13 09:55 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/dtos/InstrumentDto.java
> +    private List<OrderItemDto> orderItems;  // отсюда на страницу инструмента будет выцепляться инфо для календаря занятости
Зачем при запросе инструментов выводить информацию о заказах в которых он есть?

2022-04-13 10:50 UTC, Daria-pugacheva commented on source/core/src/main/java/ru/letmerent/core/dtos/InstrumentDto.java
> +    private List<OrderItemDto> orderItems;  // отсюда на страницу инструмента будет выцепляться инфо для календаря занятости
Ну, т.е. ты говоришь о том, что лучше отображать заказ, и из него брать инфо об инструменте. Да, соглашусь,логичнее

2022-04-16 08:33 UTC, closed without merging