Страница подтверждения заказа
siporqueno/let-me-rent pull request #55
Opened 2022-05-07 18:09 UTC by tatiananosova

2022-05-08 10:32 UTC, Daria-pugacheva approved these changes
Я написала небольшие комменты-предложения-вопросы

2022-05-08 10:32 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.html
> +        <thead>
Я бы выше добавила еще строчку (какой-нибудь span), которая бы выводилась, если cart.items.length <= 0 ,  с сообщением, что в корзине нет позиций для оформления заказа

2022-05-08 10:32 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             data: $scope.period
Не увидела по коду, а где ты в cart-confirmation  файлах задаешь значение $scope.period ? Может, я где-то просмотрела... Понятно, что это должна быть дата начала самой первой аренды в корзине и дата окончания самой последней, но не нашла, где они получаются.

2022-05-10 07:16 UTC, siporqueno requested changes

2022-05-10 07:16 UTC, siporqueno commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             data: $scope.period
```suggestion
            
```

2022-05-10 07:16 UTC, siporqueno commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             data: $scope.period
Этот параметр здесь избыточен, поскольку в корзине лежат дто-шки в которых уже есть даты начала и окончания аренды, взятые из фильтра. Они у всех инструментов одни и те же, такая у нас логика фильтрации и дальнейшего добавления в корзину.

2022-05-10 07:16 UTC, siporqueno commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             alert('Инструменты успешно забронированы');
```suggestion
             alert('Инструменты успешно арендованы');
```

2022-05-10 07:16 UTC, siporqueno commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             alert('Инструменты успешно забронированы');
Мне кажется, что кажется лучше написать "арендованы". Заказ оформлен, значит арендованы.

2022-05-10 07:16 UTC, siporqueno commented on source/core/src/main/resources/static/cart/cart.js
> +        $location.path('/cart-confirmation');
```suggestion
        $location.path('/order-confirmation');
```

2022-05-10 07:16 UTC, siporqueno commented on source/core/src/main/resources/static/cart/cart.js
> +        $location.path('/cart-confirmation');
Мне кажется, что лучше переименовать cart-confirmation в order-confirmation. Работаем с данными корзины, да, но подтверждаем заказ, а не корзину. У Фисунова эта страничка называлась order-confirmation.

2022-05-10 17:26 UTC, tatiananosova commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.html
> +        <thead>
Если в корзине нет элементов, то на странице cart не будет кнопки подтвердить заказ, то есть пользователь на эту страницу не попадет

2022-05-10 18:21 UTC, tatiananosova commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             data: $scope.period
В корзине лежит обьект Cart в котором есть `List<OrderItemDto> items` нам же для процессинга одера надо обьект OrderDto. Я пока не могу понять как перейти от List<OrderItemDto> к OrderDto.

2022-05-10 18:24 UTC, tatiananosova commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             data: $scope.period
$scope.period тут не нужен . Тут нужен обьект OrderDto. В корзине лежит обьект Cart в котором есть `List<OrderItemDto> items` нам же для процессинга одера надо обьект OrderDto. Я пока не могу понять как перейти от List<OrderItemDto> к OrderDto.
В OrderDto есть твой комментарий, что он нуждается в переработке еогда перейдём к заказам, этот момент настал похоже.

2022-05-10 18:26 UTC, tatiananosova commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             alert('Инструменты успешно забронированы');
Поправила

2022-05-10 18:32 UTC, tatiananosova commented on source/core/src/main/resources/static/cart/cart.js
> +        $location.path('/cart-confirmation');
Поправила

2022-05-11 06:24 UTC, siporqueno commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             data: $scope.period
Да, у нас есть корзина с items. По нажатию на кнопку оформить заказ на /api/v1/orders отправляется Post запрос. После этого бэк берёт корзину и из неё делает заказ. После этого в кабинете он становится виден, поскольку на странице кабинета  по запросу выводится список всех заказов пользователя.

Наверное, можно сделать оформление заказа на фронте и даже с AngularJS, но поскольку у нас всё обучение по бэку было, мне кажется, что это надо оставить бэку, а фронту просто отправлять ему запрос.

2022-05-11 06:25 UTC, siporqueno commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             data: $scope.period
> Да, у нас есть корзина с items. По нажатию на кнопку оформить заказ на /api/v1/orders отправляется Post запрос. После этого бэк берёт корзину и из неё делает заказ. После этого в кабинете он становится виден, поскольку на странице кабинета по запросу выводится список всех заказов пользователя.
> 
> Наверное, можно сделать оформление заказа на фронте и даже с AngularJS, но поскольку у нас всё обучение по бэку было, мне кажется, что это надо оставить бэку, а фронту просто отправлять ему запрос.

Да, у нас есть корзина с items. По нажатию на кнопку оформить заказ на /api/v1/orders отправляется Post запрос. После этого бэк берёт корзину и из неё делает заказ. После этого в кабинете он становится виден, поскольку на странице кабинета по запросу выводится список всех заказов пользователя.

Наверное, можно сделать оформление заказа на фронте и даже с AngularJS, но поскольку у нас всё обучение по бэку было, мне кажется, что это надо оставить бэку, а фронту просто отправлять ему запрос.

2022-05-11 13:27 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             data: $scope.period
Ага, поняла. Пока, значит небольшая заглушка в ожидании доработки бэка.

2022-05-11 13:28 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.html
> +        <thead>
Тогда вопрос снят.  Туда я не заглянула :))

2022-05-12 03:46 UTC, tatiananosova commented on source/core/src/main/resources/static/cart-confirmation/cart-confirmation.js
> +             data: $scope.period
Добавила эндпоинт перевода корзины в ордерДТО и поправила подтверждеие заказа. Теперь нужно сделать сохраниение заказа в Ордер контроллере. Посмотри пожалуйста.
@DennD

2022-05-13 13:56 UTC, TepbI4 approved these changes
Преренесем логику по формированию заказа после мержа в develop

2022-05-13 13:56 UTC, TepbI4 commented on source/core/src/main/java/ru/letmerent/core/services/impl/CartService.java
> +    public OrderDto convertCartToOrder(Principal principal, String userCartKey){
Давай перенесем в конвертер

2022-05-13 13:56 UTC, TepbI4 commented on source/core/src/main/java/ru/letmerent/core/services/impl/CartService.java
> +        LocalDateTime startDate = cart.getItems()
если все даты одинаковые, то зачем использовать 2 стрима? Нужно за 1 проход достать обе даты и засетать их в ордер

2022-05-13 16:52 UTC, merged