LMR-55 в части отправки отзывов об арендаторе
siporqueno/let-me-rent pull request #60
Opened 2022-05-09 12:50 UTC by Daria-pugacheva

Накидала функционал отправки отзывов владельца об арендаторе с учетом того, что на бэке по этому функционалу предложил сделать Артем.

1. Сделана отдельная страница для написания отзывов.
Пока нет возможности запустить посмотреть, как функционирует, сомневаюсь в двух моментах:
 - корректно ли я заполняю по умолчанию два поля модели - это строки 4 и 5 в feedback-about-renter-page.js
 - корректно ли отправляю нужных хэдер "about"  - строки 11-13 в feedback-about-renter-page.js
2. Поправила в соответствии с логикой методы в файлах с tool-history
3. Оставила TODO запрос в InstrumentRentDto, чтобы в нем появилось еще поле с айдишником арендатора (он нам нужен для отправки отзывов по предложенной Артемом логике)
4. И в UserController тоже оставила предложение сделать метод, отдающий данные о юзере по айдишнику
5. В создала глобальную переменную $rootScope.myUserIdFromProfile для реализации  отправок отзывов теперь сохраняю айдишник текущего пользователя.

2022-05-10 09:28 UTC, siporqueno requested changes

2022-05-10 09:28 UTC, siporqueno commented on source/core/src/main/resources/static/feedback-about-renter-page/feedback-about-renter-page.js
> +                "about": "USER"
```suggestion
                "about": "user"
```

2022-05-10 09:28 UTC, siporqueno commented on source/core/src/main/resources/static/feedback-about-renter-page/feedback-about-renter-page.js
> +                "about": "USER"
Мне кажется, что вместо "USER" должно быть "user", поскольку у Артема USER это константа со значением "user" : private static final String USER = "user";

2022-05-10 09:28 UTC, siporqueno commented on source/core/src/main/resources/static/feedback-about-renter-page/feedback-about-renter-page.js
> +            param: $scope.renter_comment
```suggestion
            data: $scope.renter_comment
```

2022-05-10 09:28 UTC, siporqueno commented on source/core/src/main/resources/static/feedback-about-renter-page/feedback-about-renter-page.js
> +            param: $scope.renter_comment
Поскольку в контроллере @RequestBody перед аргументом Object commentDto, его нужно отправлять в теле запроса, т.е. как data

2022-05-10 09:30 UTC, siporqueno commented on source/core/src/main/resources/static/feedback-about-renter-page/feedback-about-renter-page.js
> +                "about": "USER"
Сама отправка заголовка корректна на мой взгляд.

2022-05-10 15:26 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/feedback-about-renter-page/feedback-about-renter-page.js
> +                "about": "USER"
Спасибо! Согласна с правкой

2022-05-10 15:27 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/feedback-about-renter-page/feedback-about-renter-page.js
> +            param: $scope.renter_comment
Принято!

2022-05-11 02:54 UTC, tatiananosova commented on source/core/src/main/resources/static/tool-history/tool-history.js
> +            $http.get(contextPath + 'rent?instrumentId=' + $routeParams.toolId)//для меня непривычная форма отправки на бэк в методе GET RequestParam. К Татьяне, как автору,  вопрос про работоспособн
Это не оправка на бэк, это отбражение истории, в соответствии с эндпоинтом сделанном на бэке, работает

2022-05-13 08:09 UTC, closed without merging