Lmr 65
siporqueno/let-me-rent pull request #71
Opened 2022-05-13 19:09 UTC by Daria-pugacheva

2022-05-13 19:11 UTC, Daria-pugacheva commented
Вообще в этой ветке я делала только размещение отзывов об инструменте на его странице (последний коммит), но для удобства работы подливала в нее ветку LMR-55, поэтому так много коммитов получилось. Т.е. здесь из нового надо отсматривать только страницу tool-info.js и  tool-info.html соответственно

2022-05-14 19:04 UTC, siporqueno commented on source/core/src/main/resources/static/tool-info/tool-info.html
> +    <span style="color: mediumblue" ng-show="ascToolGrade">{{'Рейтинг инструмента:  '+ tool_grade + '  баллов по 5-бальной шкале'}}</span>
Мне кажется, что рейтинг 0 баллов по 5-бальной шкале показывать не нужно. Это я так понимаю значит что отзывов нет пока. Лучше так и написать в этом случае.

2022-05-14 19:04 UTC, siporqueno approved these changes

2022-05-15 18:16 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/tool-info/tool-info.html
> +    <span style="color: mediumblue" ng-show="ascToolGrade">{{'Рейтинг инструмента:  '+ tool_grade + '  баллов по 5-бальной шкале'}}</span>
Согласна. Поправлю

2022-05-17 02:51 UTC, tatiananosova commented
Вроде 55 ветка смержена, а изменения её всё ещё в этой ветке видны. Странновато выглядит.

2022-05-17 03:05 UTC, tatiananosova requested changes

2022-05-17 03:05 UTC, tatiananosova commented on source/core/src/main/resources/static/tool-info/tool-info.html
> +        <textarea cols="170" rows="3">{{tc.description}}</textarea>
Почему textarea? её можно редактировать, изменения правда не сохраняются, но тем не менее, можно пописать там)

2022-05-17 03:05 UTC, tatiananosova commented on source/core/src/main/resources/static/feedback-page/feedback-page.html
> +        <input class="form-control" type="number" placeholder="Введите оценку по 5-бальной шкале"
Можно выбрать любое число, как больше 5-ти, так и меньше 0. Я считаю что тут больше подходит выпадающий список.

2022-05-17 06:31 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/tool-info/tool-info.html
> +        <textarea cols="170" rows="3">{{tc.description}}</textarea>
А что предлагаешь вместо textarea? Я про редактирование не подумала. Выбрала по принципу, что размер выставила и колесико прокрутки сразу есть.

2022-05-17 06:32 UTC, Daria-pugacheva commented on source/core/src/main/resources/static/feedback-page/feedback-page.html
> +        <input class="form-control" type="number" placeholder="Введите оценку по 5-бальной шкале"
Я уже поменяла же на выпадающий список.... Странно, что не видно...

2022-05-17 07:12 UTC, merged