Lmr 54 отправка email при отправлении заказа
siporqueno/let-me-rent pull request #81
Opened 2022-05-16 19:31 UTC by framzik

2022-05-17 08:05 UTC, Haazaad requested changes

2022-05-17 08:05 UTC, Haazaad commented on source/core/src/main/resources/application.yml
> +    password: Ferdinand447!
Не очень хорошая практика светить пароль, лучше предварительно его шифрануть и в пропертях указать хэш, а далее при использовании дешифровать

2022-05-17 08:05 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/EmailServiceImpl.java
> +        session = Session.getInstance(props, null);
Выглядит, что лучше завернуть в try - catch и нет закрытия сессии

2022-05-17 19:45 UTC, framzik commented on source/core/src/main/resources/application.yml
> +    password: Ferdinand447!
сделал

2022-05-17 19:46 UTC, framzik commented on source/core/src/main/java/ru/letmerent/core/services/impl/EmailServiceImpl.java
> +        session = Session.getInstance(props, null);
исправил

2022-05-19 04:55 UTC, Haazaad approved these changes

2022-05-19 19:04 UTC, merged