LMR-75 - оживление страницы редактирования инфо об инструменте
siporqueno/let-me-rent pull request #83
Opened 2022-05-17 08:38 UTC by Daria-pugacheva

Убрала лишнюю страницу с фронта и лишние комментарии на странице с инфо об инструменте.

Из профиля убрала кнопки Удалить и Снять с аренды (и их функции)
По странице редактирования инструмента. Пока есть форма редактирования простых полей (категория, название, марка, цена, залог, описание).
По поводу редактирования даты окончания аренды, чтобы снять с аренды, как обсудили на скраме 16.05.22, написала комментарий в Трелло - примем решение по бэку и добавлю тогда (на бэке мне нужно будет подкорректировать ДТО-шку для этого, а Диме логику расчета интервалов доступности)
ПО ПОВОДУ РЕДАКТИРОВАНИЯ ФОТОК. Пока в эту форму не добавляла. Мне видится, что для этого надо отдельно ниже формы со всеми данными как-то выводить имеющиеся фотки с кнопочками "Удалить", чтобы можно было их удалять, и плюс input-поле, чтобы добавлять новые фотки. Т.е. как-то на фронте надо будет редактировать лист фоток (из стартового будут удаляться имеющиеся и добавляться новые фото, а уже результирующий лист pictureUrls отправляться на бэк) Пока в голове не укладывается, как это лучше сделать. Возможно, у Николая, т.к. разбирался с добавлением фоток, есть видение, как это оптимально реализовать? (я посмотрела реализацию отражения фото на странице и добавления, пока все это в голове крутится, но решение, как это объединить для редактирования, пока не нащупывается)

2022-05-17 11:18 UTC, siporqueno reviewed
По endDate ответил в карточке Trello. По изменениям фотографий - как обсудили выносим в отдельную задачу, чтобы не задерживать эту.

2022-05-18 09:55 UTC, siporqueno commented on source/core/src/main/resources/static/edit-tool/edit-tool.html
> +        <p>Если вы хотите снять инструмент с аренды, поменяйте дату окончания предоставления инструмента в аренду на текущую:</p>
```suggestion
        <p>Если вы хотите сократить ограничить дальнейшую аренду инструмента, вы можете поменять дату окончания предоставления инструмента в аренду на любую дату после даты окончания крайней аренды: {{earliestPossibleEndDate}}</p>
```

2022-05-18 14:14 UTC, Daria-pugacheva commented
Проверка работоспособности вывела меня на сложности с десериализацией из-за наличия в InstrumentInfoDto полей, которые являются LоcalDateTime. Написала в коммите, что  добавила  в код. Принт-скрин с ошибкой прикрепила к карточке в Трелло.  Пока успела только увидеть, какие сыплются ошибки. 
В ревьюеры добавила Алексея, т.к. он помогал с доп.полями в InstrumentInfoDto,  и Артема, т.к. он, если не ошибаюсь, участвовал в решении аналогичной проблемы с корзиной. 
Я сильно не уверена, что оперативно сумею разобраться с тем, как решить эту проблему с сериализацией.

2022-05-19 07:03 UTC, Haazaad requested changes

2022-05-19 07:03 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/dto/IntervalDto.java
> +import lombok.*;
Избавиться от wildcard, необходимо проводить импорт только того, что необходимо для работы

2022-05-19 11:49 UTC, siporqueno reviewed
Добавил InstrumentInfoDtoDeserializer и аннотацию в InstrumentInfoDto.

В десериализаторе надо будет ещё мне допилить преобразование урлов картинок и интервалов. Проверил - изменяет, интервалы и урлы ест-но пока пустые.

2022-05-20 06:35 UTC, Haazaad requested changes

2022-05-20 06:35 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentInfoDto.java
> +import lombok.*;
Избавится от wildcard

2022-05-20 06:35 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentInfoDtoDeserializer.java
> +        System.out.println(id);
А зачем это в консоль выводить?

2022-05-20 06:35 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentInfoDtoDeserializer.java
> +public class InstrumentInfoDtoDeserializer extends StdDeserializer<InstrumentInfoDto> {
А смысл этого десериализатора? Неужели ObjectMapper не подхватает?

2022-05-20 09:23 UTC, siporqueno commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentInfoDtoDeserializer.java
> +        System.out.println(id);
> А зачем это в консоль выводить?

Когда писал десериализатор, смотрел что он выдает. Много лишних кавычек выловил из-за которых фронт инструмент не менял. Уберу все sout.

2022-05-20 09:25 UTC, siporqueno commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentInfoDtoDeserializer.java
> +public class InstrumentInfoDtoDeserializer extends StdDeserializer<InstrumentInfoDto> {
Не подхватывает, закомментируй @JsonDeserialize(using = InstrumentInfoDtoDeserializer.class) в InstrumentInfoDto и будут ошибки.

2022-05-20 15:33 UTC, siporqueno approved these changes

2022-05-21 06:27 UTC, siporqueno commented
Не надо пока мержить эту ветку. InstrumentInfoDtoDeserializer срабатывает, естественно, и при добавлении нового инструмента и его надо будет править, чтобы он правильно срабатывал при добавлении. Сейчас срабатывает не правильно и добавление не работает с ним.

2022-05-22 13:35 UTC, merged