Описание контракта проекта
siporqueno/let-me-rent pull request #9
Opened 2022-04-13 07:29 UTC by DennD

Добавили SWAGGER на OpenApi

Feature - LMR-15(add_contract)

2022-04-13 15:54 UTC, Haazaad requested changes

2022-04-13 15:54 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/LetMeRentApplication.java
> +        var application = SpringApplication.run(LetMeRentApplication.class, args);
Синтаксический сахар это прекрасно, но чтобы не путаться, лучше указывать название класса, либо интерфейса

2022-04-13 15:54 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/config/SwaggerProperties.java
> +import lombok.*;
Избавляемся от wildcard, лучше испортить только то, что используется

2022-04-13 15:54 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/controllers/IAuthController.java
> -package ru.letmerent.core.controllers;
Зачем ремувить интерфейсы?

2022-04-13 15:54 UTC, Haazaad commented on source/pom.xml
> +            <groupId>org.springframework.boot</groupId>
Тут видится зависимость лишняя, т.к. идёт добавление в другом модуле и никто больше не не пользует

2022-04-13 15:54 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/config/SwaggerProperties.java
> +    public static class Contact {
А где то ещё используется этот класс?

2022-04-13 17:41 UTC, siporqueno commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentDto.java
> +    List<OrderItemDto> orderItems;
```suggestion
    
```

2022-04-13 17:47 UTC, siporqueno commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentDto.java
> +    List<OrderItemDto> orderItems;
Это можно убрать, как и в сущности. В Dto для странички инструмента понадобится коллекция интервалов его доступности, но можно будет от этого Dto унаследоваться и добавить.

2022-04-13 18:15 UTC, siporqueno commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentDto.java
> +
```suggestion
   
```

2022-04-13 21:20 UTC, Daria-pugacheva commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentDto.java
> +    List<OrderItemDto> orderItems;
Мы обсуждали тему с наследованием для расширения кол-ва информации в Dto, но пока решили, что обойдемся одним масштабным Dto , а дальше уже посмотрим и по ходу движения оптимизируем.

2022-04-14 04:29 UTC, DennD commented on source/core/src/main/java/ru/letmerent/core/controllers/IAuthController.java
> -package ru.letmerent.core.controllers;
OpenApi не захотел с интерфейсами работать, только с классами запахал - странное поведение.

2022-04-14 04:31 UTC, DennD commented on source/core/src/main/java/ru/letmerent/core/config/SwaggerProperties.java
> +    public static class Contact {
Только в SwaggerConfig

2022-04-14 05:03 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/controllers/IAuthController.java
> -package ru.letmerent.core.controllers;
Так все таки зачем удалять интерфейсы, если можно их имплементировать, а в OpenApi передавать конкретные классы для использования

2022-04-14 05:04 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/config/SwaggerProperties.java
> +    public static class Contact {
Тогда это приватный класс, не стоит его выставлять жопой наружу, ну и наверное не статический

2022-04-14 05:15 UTC, Haazaad requested changes

2022-04-14 05:15 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/config/SwaggerProperties.java
> +@Getter
Зачем во все классы подряд пихать геттеры и сеттеры?
Действительно ли для данного класса нужно получать все извне и инициализировать извне?

2022-04-14 09:25 UTC, siporqueno commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentDto.java
> +
```suggestion
    @Schema(description = "Бренд инструмента", example = "Bosch")
    String brandName;
    
```

2022-04-14 09:27 UTC, siporqueno commented on source/core/src/main/java/ru/letmerent/core/dto/InstrumentDto.java
> +
Сущности производитель не будет. Переименовал brand в brandName как в сущности Brand.

2022-04-14 18:51 UTC, Haazaad approved these changes

2022-04-14 18:52 UTC, merged