Lmr 74-2 - обновление данных пользователя. Исключила правку файла по внесению данных в БД
siporqueno/let-me-rent pull request #95
Opened 2022-05-18 11:35 UTC by Daria-pugacheva

Попытка № 2.
Убрала лишнюю страницу
Добавила на фронте функционал по изменению данных пользователя
Добавила на бэке методы по модификации пользователя.

2022-05-18 17:59 UTC, framzik approved these changes

2022-05-19 04:58 UTC, Haazaad requested changes

2022-05-19 04:58 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/UserService.java
> +    public void modifyUser(UserDto userDto) {
А чем этот метод отличается от saveUser?

2022-05-19 04:58 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/controllers/UserController.java
> +//    @Operation(summary = "Модификация пользовательских данных")
для исключения загромождения кода убрать лишние комментарии

2022-05-19 06:53 UTC, Daria-pugacheva commented on source/core/src/main/java/ru/letmerent/core/services/impl/UserService.java
> +    public void modifyUser(UserDto userDto) {
Ну... смотри в просто сохранении мы создаем новый объект и кладем его в БД. 
А  в модификации достаем из БД существующий объект, он болтается в контексте, мы в коде меняем какие-то его поля, а при сохранении заменяются его поля в объекте, который был в контексте, и кладутся в базу обратно на то же место как бы. 
Или я что-то недопонимаю и разницы действительно нет? т.е. в методе save просто конвертнем из ДТО-шки сущность и она окажется с тем же айдишником, что имеющаяся в базе, и  произойдет обновление имеющейся в базе?

2022-05-19 06:56 UTC, Daria-pugacheva commented on source/core/src/main/java/ru/letmerent/core/controllers/UserController.java
> +//    @Operation(summary = "Модификация пользовательских данных")
Убрала

2022-05-19 06:59 UTC, Daria-pugacheva commented on source/core/src/main/java/ru/letmerent/core/controllers/UserController.java
> +//    @Operation(summary = "Модификация пользовательских данных")
Смотри, я тебе ответила сейчас => кнопку Resolve Conversation  ты нажимаешь, как итог того, что согласен с правками? или я, если уверена, что верно откликнулась на твое предложение по правкам? (после того, как я всем все сломала, глаз дергается... поэтому уточняю, видимо,  я какие-то моменты согласования правок недопонимаю вдруг)

2022-05-19 07:05 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/services/impl/UserService.java
> +    public void modifyUser(UserDto userDto) {
> Ну... смотри в просто сохранении мы создаем новый объект и кладем его в БД. А в модификации достаем из БД существующий объект, он болтается в контексте, мы в коде меняем какие-то его поля, а при сохранении заменяются его поля в объекте, который был в контексте, и кладутся в базу обратно на то же место как бы. Или я что-то недопонимаю и разницы действительно нет? т.е. в методе save просто конвертнем из ДТО-шки сущность и она окажется с тем же айдишником, что имеющаяся в базе, и произойдет обновление имеющейся в базе?

1. дока https://docs.spring.io/spring-data/jpa/docs/current/api/
2. hibernate сам понимает, что он сохраняет. ну и дока выше

2022-05-19 07:23 UTC, Haazaad commented on source/core/src/main/java/ru/letmerent/core/controllers/UserController.java
> +//    @Operation(summary = "Модификация пользовательских данных")
Как итог, что я согласен я жму Approve, а не просмотр комментария

2022-05-19 07:31 UTC, Daria-pugacheva commented on source/core/src/main/java/ru/letmerent/core/services/impl/UserService.java
> +    public void modifyUser(UserDto userDto) {
Поправила

2022-05-19 07:57 UTC, Haazaad approved these changes

2022-05-19 08:11 UTC, merged